services:
  nginx:
    logging:
      driver: "awslogs"
      options:
        awslogs-region: ${AWS_REGION}
        awslogs-group: ${AWS_LOG_GROUP}

  strapi:
    logging:
      driver: "awslogs"
      options:
        awslogs-region: ${AWS_REGION}
        awslogs-group: ${AWS_LOG_GROUP}

  strapi_db:
    logging:
      driver: "awslogs"
      options:
        awslogs-region: ${AWS_REGION}
        awslogs-group: ${AWS_LOG_GROUP}

  db_backup:
    image: eeshugerman/postgres-backup-s3:16
    restart: always
    links:
      - strapi_db
    depends_on:
      - strapi_db
    networks:
      - database
    environment:
      S3_ACCESS_KEY_ID: ${BACKUP_AWS_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${BACKUP_AWS_ACCESS_SECRET}
      S3_REGION: ${AWS_REGION}
      S3_BUCKET: ${BACKUP_AWS_BUCKET_NAME}
      S3_PREFIX: strapi_db
      POSTGRES_DATABASE: strapi
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      SCHEDULE: 0 0 * * *
      BACKUP_KEEP_DAYS: 30
    logging:
      driver: "awslogs"
      options:
        awslogs-region: ${AWS_REGION}
        awslogs-group: ${AWS_LOG_GROUP}

  webhooks:
    logging:
      driver: "awslogs"
      options:
        awslogs-region: ${AWS_REGION}
        awslogs-group: ${AWS_LOG_GROUP}

  # auth:
  #   logging:
  #     driver: "awslogs"
  #     options:
  #       awslogs-region: ${AWS_REGION}
  #       awslogs-group: ${AWS_LOG_GROUP}

  # auth_redis:
  #   logging:
  #     driver: "awslogs"
  #     options:
  #       awslogs-region: ${AWS_REGION}
  #       awslogs-group: ${AWS_LOG_GROUP}
